controller_list:
  - name: fake_ur5e_arm_controller
    type: $(arg execution_type)
    joints:
      - ur5e_shoulder_pan_joint
      - ur5e_shoulder_lift_joint
      - ur5e_elbow_joint
      - ur5e_wrist_1_joint
      - ur5e_wrist_2_joint
      - ur5e_wrist_3_joint
  - name: fake_ur16e_arm_controller
    type: $(arg execution_type)
    joints:
      - ur16e_shoulder_pan_joint
      - ur16e_shoulder_lift_joint
      - ur16e_elbow_joint
      - ur16e_wrist_1_joint
      - ur16e_wrist_2_joint
      - ur16e_wrist_3_joint
  - name: fake_ur5e_gripper_controller
    type: $(arg execution_type)
    joints:
      - finger_joint
initial:  # Define initial robot poses.
  - group: ur5e_arm
    pose: Home_ur5e
  - group: ur16e_arm
    pose: Home_ur16e